### ISSUE TITLE
Instructor Feedback Week 4

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [woestmab/IndieSpringProject#4]
Nice work on the database and screen design.

- [x] Are start and end on appointments date/time? They are represented as int and just wanted to make sure I'm understanding the intent.
- [x] Looks like the bootstrap calendar will provide some great formatting - how will you connect that with your java code/java pojos/entities?
- [x] I like that you have in your plan to do UML and ER diagramming.  Do you feel your project plan has enough development detail to keep you on track? For example, this week we are learning how to handle user log in/authentication/authorization. Would it be helpful to add that as a task or two to your plan? 
- [x] Thanks for being so willing to share what you learn on Slack. Great job!

**Comment by woestmab** [comment]
Thank you, I appreciate the feedback.

1.  The start and end appointment times are integers that represent milliseconds according to the calendar documentation.  I went to a site that would do conversions for me in order to figure out what the numbers needed to be for the scheduled appointments I had in class.
2.  The bootstrap portion of the site will be all in the css and the elements of html will have them embedded in the templates.
3.  I think that it's a great idea to add the login to the list.  I have it on my diagram but I forgot to add it into the plan documentation and it would be helpful to have more milestones to keep tabs of progress.  I will add them to my project plan.
4. I love sharing!  It's my pleasure to help others see what awesome technology exists out there.  Sharing also helps me gain a better understanding by explaining things I've researched on my own.

I will close this ticket when I've made the changes you've suggested.
